[package]
name = "gdnative-sys"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.52.0"
proc-macro2 = "1.0.6"
quote = "1.0.2"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
