[package]
name = "gdnative-sys"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.51.1"
lazy_static = "1.4.0"
regex = "1.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
