[package]
name = "rust"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative-sys = { path = "../../../refactor/gdnative-sys" }
